package com.shabalin13.kinopoisk.domain.model

data class MediaItem(
    val id: Int,
    val name: String,
    val type: MediaItemType,
    val isSeries: Boolean,
    val alternativeName: String?,
    val year: Int?,
    val releaseYears: MediaItemReleaseYears?,
    val description: String?,
    val slogan: String?,
    val status: MediaItemStatus?,
    val ratings: MediaItemRatings?,
    val movieLength: Int?,
    val ageRating: Int?,
    val posterUrl: String?,
    val genres: List<String>,
    val countries: List<String>,
    val actors: List<MediaItemActor>,
    val contributors: List<MediaItemContributor>,
    val seasonsInfo: List<MediaItemSeasonInfo>,
    val budget: MediaItemBudget?,
    val fees: MediaItemFees?,
    val premieres: MediaItemPremieres?,
    val linkedMediaItems: List<RelatedMediaItem>,
    val similarMediaItems: List<RelatedMediaItem>,
    val facts: List<MediaItemFact>,
    val bloopers: List<MediaItemBlooper>,
    val videos: List<MediaItemVideo>,
)
