package com.shabalin13.kinopoisk.domain.mediaDetails.models

data class MediaDetails(
    val id: Int,
    val name: String,
    val type: MediaDetailsType,
    val isSeries: Boolean,
    val alternativeName: String?,
    val year: Int?,
    val releaseYears: MediaDetailsReleaseYears?,
    val description: String?,
    val slogan: String?,
    val status: MediaDetailsStatus?,
    val ratings: MediaDetailsRatings?,
    val movieLength: Int?,
    val ageRating: Int?,
    val posterUrl: String?,
    val genres: List<String>,
    val countries: List<String>,
    val actors: List<MediaDetailsActor>,
    val contributors: List<MediaDetailsContributor>,
    val seasonsInfo: List<MediaDetailsSeasonInfo>,
    val budget: MediaDetailsBudget?,
    val fees: MediaDetailsFees?,
    val premieres: MediaDetailsPremieres?,
    val linkedMediaItems: List<MediaDetailsLinkedMediaItem>,
    val similarMediaItems: List<MediaDetailsSimilarMediaItem>,
    val facts: List<MediaDetailsFact>,
    val bloopers: List<MediaDetailsBlooper>,
    val videos: List<MediaDetailsVideo>,
)
