package com.shabalin13.kinopoisk.ui.theme

import androidx.compose.ui.graphics.Color

object KinopoiskLightThemeColors {
    val primaryLight = Color(0xFFA33E00)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFFF6600)
    val onPrimaryContainerLight = Color(0xFF561D00)
    val secondaryLight = Color(0xFF99461D)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFFE9565)
    val onSecondaryContainerLight = Color(0xFF752D03)
    val tertiaryLight = Color(0xFF6B5F00)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFC0AC22)
    val onTertiaryContainerLight = Color(0xFF494000)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF93000A)
    val backgroundLight = Color(0xFFFFF8F6)
    val onBackgroundLight = Color(0xFF261812)
    val surfaceLight = Color(0xFFFFF8F6)
    val onSurfaceLight = Color(0xFF261812)
    val surfaceVariantLight = Color(0xFFFFDBCD)
    val onSurfaceVariantLight = Color(0xFF5A4136)
    val outlineLight = Color(0xFF8E7164)
    val outlineVariantLight = Color(0xFFE3BFB1)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF3D2D26)
    val inverseOnSurfaceLight = Color(0xFFFFEDE7)
    val inversePrimaryLight = Color(0xFFFFB596)
    val surfaceDimLight = Color(0xFFF0D4CA)
    val surfaceBrightLight = Color(0xFFFFF8F6)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFFFF1EC)
    val surfaceContainerLight = Color(0xFFFFE9E1)
    val surfaceContainerHighLight = Color(0xFFFEE2D8)
    val surfaceContainerHighestLight = Color(0xFFF8DDD2)
}

object KinopoiskDarkThemeColors {
    val primaryDark = Color(0xFFFFB596)
    val onPrimaryDark = Color(0xFF581E00)
    val primaryContainerDark = Color(0xFFFF6600)
    val onPrimaryContainerDark = Color(0xFF561D00)
    val secondaryDark = Color(0xFFFFB596)
    val onSecondaryDark = Color(0xFF581E00)
    val secondaryContainerDark = Color(0xFF7D3208)
    val onSecondaryContainerDark = Color(0xFFFFA177)
    val tertiaryDark = Color(0xFFDDC83E)
    val onTertiaryDark = Color(0xFF383100)
    val tertiaryContainerDark = Color(0xFFC0AC22)
    val onTertiaryContainerDark = Color(0xFF494000)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF1D100A)
    val onBackgroundDark = Color(0xFFF8DDD2)
    val surfaceDark = Color(0xFF1D100A)
    val onSurfaceDark = Color(0xFFF8DDD2)
    val surfaceVariantDark = Color(0xFF5A4136)
    val onSurfaceVariantDark = Color(0xFFE3BFB1)
    val outlineDark = Color(0xFFAA8A7D)
    val outlineVariantDark = Color(0xFF5A4136)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFF8DDD2)
    val inverseOnSurfaceDark = Color(0xFF3D2D26)
    val inversePrimaryDark = Color(0xFFA33E00)
    val surfaceDimDark = Color(0xFF1D100A)
    val surfaceBrightDark = Color(0xFF47352E)
    val surfaceContainerLowestDark = Color(0xFF180B06)
    val surfaceContainerLowDark = Color(0xFF261812)
    val surfaceContainerDark = Color(0xFF2B1C16)
    val surfaceContainerHighDark = Color(0xFF362620)
    val surfaceContainerHighestDark = Color(0xFF42312A)
}

object RatingColors {
    val high = Color(0xFF4CAF50)
    val medium = Color(0xFF9E9E9E)
    val low = Color(0xFFF44336)
}
