package com.shabalin13.kinopoisk.ui.theme

import androidx.compose.ui.graphics.Color

object KinopoiskLightThemeColors {
    val primaryLight = Color(0xFFFF5500)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFFAB694)
    val onPrimaryContainerLight = Color(0xFF000000)
    val secondaryLight = Color(0xFFCC6A2C)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFFFD8B5)
    val onSecondaryContainerLight = Color(0xFF000000)
    val tertiaryLight = Color(0xFF43A800)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFA8E500)
    val onTertiaryContainerLight = Color(0xFF000000)
    val errorLight = Color(0xFFC00000)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFE00000)
    val onErrorContainerLight = Color(0xFF000000)
    val backgroundLight = Color(0xFFFFFFFF)
    val onBackgroundLight = Color(0xFF000000)
    val surfaceLight = Color(0xFFFFFFFF)
    val onSurfaceLight = Color(0xFF000000)
    val surfaceVariantLight = Color(0xFFE2E2E2)
    val onSurfaceVariantLight = Color(0xFF474747)
    val outlineLight = Color(0xFF777777)
    val outlineVariantLight = Color(0xFFC6C6C6)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF303030)
    val inverseOnSurfaceLight = Color(0xFFFFFFFF)
    val inversePrimaryLight = Color(0xFFFF5500)
    val surfaceDimLight = Color(0xFFDADADA)
    val surfaceBrightLight = Color(0xFFFFFFFF)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF3F3F3)
    val surfaceContainerLight = Color(0xFFEEEEEE)
    val surfaceContainerHighLight = Color(0xFFE8E8E8)
    val surfaceContainerHighestLight = Color(0xFFE2E2E2)
}

object KinopoiskDarkThemeColors {
    val primaryDark = Color(0xFFFF5500)
    val onPrimaryDark = Color(0xFFFFFFFF)
    val primaryContainerDark = Color(0xFFD18768)
    val onPrimaryContainerDark = Color(0xFF000000)
    val secondaryDark = Color(0xFFCC6A2C)
    val onSecondaryDark = Color(0xFFFFFFFF)
    val secondaryContainerDark = Color(0xFFD6A779)
    val onSecondaryContainerDark = Color(0xFF000000)
    val tertiaryDark = Color(0xFF43A800)
    val onTertiaryDark = Color(0xFFFFFFFF)
    val tertiaryContainerDark = Color(0xFF82B200)
    val onTertiaryContainerDark = Color(0xFF000000)
    val errorDark = Color(0xFFE00000)
    val onErrorDark = Color(0xFFFFFFFF)
    val errorContainerDark = Color(0xFFC00000)
    val onErrorContainerDark = Color(0xFF000000)
    val backgroundDark = Color(0xFF000000)
    val onBackgroundDark = Color(0xFFFFFFFF)
    val surfaceDark = Color(0xFF000000)
    val onSurfaceDark = Color(0xFFFFFFFF)
    val surfaceVariantDark = Color(0xFF474747)
    val onSurfaceVariantDark = Color(0xFFC6C6C6)
    val outlineDark = Color(0xFF919191)
    val outlineVariantDark = Color(0xFF474747)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE2E2E2)
    val inverseOnSurfaceDark = Color(0xFF000000)
    val inversePrimaryDark = Color(0xFFFF5500)
    val surfaceDimDark = Color(0xFF000000)
    val surfaceBrightDark = Color(0xFF393939)
    val surfaceContainerLowestDark = Color(0xFF000000)
    val surfaceContainerLowDark = Color(0xFF1b1b1b)
    val surfaceContainerDark = Color(0xFF1f1f1f)
    val surfaceContainerHighDark = Color(0xFF2a2a2a)
    val surfaceContainerHighestDark = Color(0xFF353535)
}

object RatingColors {
    val high = Color(0xFF4CAF50)
    val medium = Color(0xFF9E9E9E)
    val low = Color(0xFFF44336)
}
